/*
 * Dacar C++ port — LWW-Element-Set CRDT tests (§6, §9, §12, §13.4).
 *
 * Byte-exact state snapshots (§13.4) are generated by the canonical Python
 * implementation: given the same delta streams, both implementations must
 * converge to byte-identical state (work doc #16, Phase 1 exit criteria).
 *
 * Licensed under the EUPL-1.2 (see repository root).
 */

#include <unity.h>

#include "TestUtil.h"

#include <stdexcept>

using namespace Dacar;
using namespace DacarTest;

void setUp(void) {}
void tearDown(void) {}

static void replaySteps(StateVector& state, const DacarFixtures::StateStep* steps, size_t count, const std::vector<NamespaceHasher>& hashers) {
	for (size_t i = 0; i < count; i++) {
		TEST_ASSERT_EQUAL_UINT8(steps[i].expect, applyStep(state, steps[i], hashers));
	}
}

void testStateSnapshotsMatchCanonical() {
	for (size_t i = 0; i < DacarFixtures::STATE_CASE_COUNT; i++) {
		const auto& c = *DacarFixtures::STATE_CASES[i];
		auto hashers = hashersFor(c.salt_hex, c.legacy_hex);
		StateVector state(c.horizon_days);
		replaySteps(state, c.steps, c.step_count, hashers);

		if (c.step_b_count > 0) {
			// Merge case: `expected` is the post-merge snapshot (state B
			// merged into A) — assert it only after the merge.
			StateVector state_b(c.horizon_days);
			replaySteps(state_b, c.steps_b, c.step_b_count, hashers);
			state.merge(state_b);
			TEST_ASSERT_EQUAL_STRING(c.expected_hex, state.to_payload().toHex().c_str());

			// The opposite merge direction resolves to the same state
			// (same tuple hashes, same activity), differing only in row
			// order (insertion order is preserved).
			StateVector state_a2(c.horizon_days);
			replaySteps(state_a2, c.steps, c.step_count, hashers);
			StateVector state_b2(c.horizon_days);
			replaySteps(state_b2, c.steps_b, c.step_b_count, hashers);
			state_b2.merge(state_a2);
			TEST_ASSERT_EQUAL_size_t(state.size(), state_b2.size());
			for (const auto& entry : state.entries()) {
				const Dacar::StateVector::Entry* other = state_b2.get(entry.tuple.hash());
				TEST_ASSERT_NOT_NULL(other);
				TEST_ASSERT_EQUAL_UINT8(entry.active(), other->active());
			}
		}
		else {
			TEST_ASSERT_EQUAL_STRING(c.expected_hex, state.to_payload().toHex().c_str());
		}

		if (c.prune_now_ms >= 0) {
			size_t pruned = state.prune(c.prune_now_ms);
			TEST_ASSERT_EQUAL_size_t(c.pruned, pruned);
			TEST_ASSERT_EQUAL_STRING(c.expected_after_hex, state.to_payload().toHex().c_str());
		}
	}
}

void testSnapshotRoundtrip() {
	const auto& c = *DacarFixtures::STATE_CASES[0];
	auto hashers = hashersFor(c.salt_hex, c.legacy_hex);
	StateVector state(c.horizon_days);
	replaySteps(state, c.steps, c.step_count, hashers);
	RNS::Bytes payload = state.to_payload();
	StateVector restored = StateVector::from_payload(payload, c.horizon_days);
	TEST_ASSERT_EQUAL_size_t(state.size(), restored.size());
	// Snapshot roundtrip is byte-stable.
	TEST_ASSERT_EQUAL_STRING(
		payload.toHex().c_str(), restored.to_payload().toHex().c_str()
	);
}

void testMalformedSnapshotRejected() {
	TEST_ASSERT_THROW(StateVector::from_payload(RNS::Bytes("garbage")), std::invalid_argument);
	// A valid array whose rows are not 7-element arrays.
	TEST_ASSERT_THROW(
		StateVector::from_payload(bytesFromHex("9101")), std::invalid_argument
	);
}

void testQueries() {
	const auto& c = *DacarFixtures::STATE_CASES[0];
	auto hashers = hashersFor(c.salt_hex, c.legacy_hex);
	StateVector state(c.horizon_days);
	replaySteps(state, c.steps, c.step_count, hashers);

	// steps: grant (BOB), grant (A2 as grantee), revoke BOB, re-grant BOB.
	// The re-granted tuple is active again; iter_entries exposes both.
	size_t active = 0;
	for (const Tuple* t : state.active_tuples()) {
		active++;
		(void)t;
	}
	TEST_ASSERT_EQUAL_size_t(state.size(), active);

	// is_active reflects grant/re-grant semantics via the tuple hash.
	NamespaceHasher& hasher = hashers[0];
	Tuple bob = Tuple::from_plaintext(
		"sensor:wind", "calibrate",
		bytesFromHex(c.steps[0].grantee_hex), bytesFromHex(c.steps[0].issuer_hex), hasher
	);
	TEST_ASSERT_TRUE(state.is_active(bob.hash()));
	TEST_ASSERT_TRUE(state.contains(bob.hash()));
	const Dacar::StateVector::Entry* entry = state.get(bob.hash());
	TEST_ASSERT_NOT_NULL(entry);
	// The re-grant (NOW+4) dominates the revoke (NOW+3).
	TEST_ASSERT_TRUE(entry->has_add);
	TEST_ASSERT_TRUE(entry->has_remove);
	TEST_ASSERT_TRUE(entry->add_ts > entry->remove_ts);

	// Unknown tuple hash -> inactive, no entry.
	RNS::Bytes unknown(32);
	memset(unknown.writable(32), 1, 32);
	TEST_ASSERT_FALSE(state.is_active(unknown));
	TEST_ASSERT_NULL(state.get(unknown));
}

void testDeletionHorizonDefaults() {
	StateVector state;
	TEST_ASSERT_EQUAL_INT(DEFAULT_DELETION_HORIZON_DAYS, state.deletion_horizon_days());
	StateVector custom(90);
	TEST_ASSERT_EQUAL_INT(90, custom.deletion_horizon_days());
}

int runUnityTests(void) {
	UNITY_BEGIN();
	RUN_TEST(testStateSnapshotsMatchCanonical);
	RUN_TEST(testSnapshotRoundtrip);
	RUN_TEST(testMalformedSnapshotRejected);
	RUN_TEST(testQueries);
	RUN_TEST(testDeletionHorizonDefaults);
	return UNITY_END();
}

int main(void) {
	return runUnityTests();
}

#ifdef ARDUINO
void setup() {
	delay(2000);
	runUnityTests();
}
void loop() {}
#endif

void app_main() {
	runUnityTests();
}
