/*
 * Dacar C++ port — Namespace Label Privacy tests (§3.3).
 *
 * Byte-exact vectors are generated by the canonical Python implementation
 * (test/tools/generate_fixtures.py).
 *
 * Licensed under the EUPL-1.2 (see repository root).
 */

#include <unity.h>

#include "TestUtil.h"

#include <stdexcept>

using namespace Dacar;
using namespace DacarTest;

void setUp(void) {
	// set stuff up here
}

void tearDown(void) {
	// clean stuff up here after each test
}

void testRelationHashesMatchCanonical() {
	for (const auto& c : DacarFixtures::NS_RELATION_CASES) {
		NamespaceHasher hasher(bytesFromHex(c.salt_hex));
		RNS::Bytes hash = hasher.hash_relation(c.relation);
		TEST_ASSERT_EQUAL_STRING(c.hash_hex, hash.toHex().c_str());
	}
}

void testObjectHashingMatchesCanonical() {
	for (const auto& c : DacarFixtures::NS_OBJECT_CASES) {
		NamespaceHasher hasher(bytesFromHex(c.salt_hex));
		auto [hashes, wildcard] = hasher.hash_object(c.object);
		TEST_ASSERT_EQUAL_UINT8(c.wildcard, wildcard);
		auto expected = bytesVecFromHex(c.segments_hex);
		TEST_ASSERT_EQUAL_size_t(expected.size(), hashes.size());
		for (size_t i = 0; i < expected.size(); i++) {
			TEST_ASSERT_EQUAL_STRING(expected[i].toHex().c_str(), hashes[i].toHex().c_str());
		}
	}
}

void testIdTagMatchesCanonical() {
	for (const auto& c : DacarFixtures::NS_IDTAG_CASES) {
		NamespaceHasher hasher(bytesFromHex(c.salt_hex));
		TEST_ASSERT_EQUAL_STRING(c.tag_hex, hasher.id_tag().toHex().c_str());
	}
}

void testCovers() {
	for (const auto& c : DacarFixtures::COVERS_CASES) {
		auto tuple_hashes = bytesVecFromHex(c.tuple_hex);
		auto request_hashes = bytesVecFromHex(c.request_hex);
		TEST_ASSERT_EQUAL_UINT8(c.expected, covers(tuple_hashes, c.wildcard, request_hashes));
	}
}

void testTruncatedTo16Bytes() {
	NamespaceHasher hasher;
	TEST_ASSERT_EQUAL_size_t(HASH_SIZE, hasher.hash_relation("admin").size());
	auto [hashes, _w] = hasher.hash_object("a:b:c");
	for (const auto& h : hashes) {
		TEST_ASSERT_EQUAL_size_t(HASH_SIZE, h.size());
	}
}

void testDefaultSaltIsFailOpenNulls() {
	RNS::Bytes expected;
	memset(expected.writable(SALT_SIZE), 0, SALT_SIZE);
	TEST_ASSERT_TRUE(DEFAULT_SALT() == expected);
	// The default-constructed hasher uses the null salt.
	NamespaceHasher hasher;
	NamespaceHasher explicit_nulls(expected);
	TEST_ASSERT_TRUE(hasher.hash_relation("x") == explicit_nulls.hash_relation("x"));
}

void testSaltSensitivity() {
	// NS_RELATION_CASES are grouped by salt: index 0 uses the primary
	// fixture salt, index 6 the legacy salt.
	NamespaceHasher a(bytesFromHex(DacarFixtures::NS_RELATION_CASES[0].salt_hex));
	NamespaceHasher b(bytesFromHex(DacarFixtures::NS_RELATION_CASES[6].salt_hex));
	TEST_ASSERT_TRUE(a.salt() != b.salt());
	TEST_ASSERT_TRUE(a.hash_relation("admin") != b.hash_relation("admin"));
}

void testSaltMustBe32Bytes() {
	TEST_ASSERT_THROW(NamespaceHasher(RNS::Bytes("short")), std::invalid_argument);
	RNS::Bytes too_long;
	memset(too_long.writable(33), 1, 33);
	TEST_ASSERT_THROW(NamespaceHasher(too_long), std::invalid_argument);
}

void testSplitMatchesPythonSemantics() {
	// Python "".split(":") == [""] — one empty segment.
	auto empty = split("");
	TEST_ASSERT_EQUAL_size_t(1, empty.size());
	TEST_ASSERT_EQUAL_STRING("", empty[0].c_str());
	auto two = split("a:b");
	TEST_ASSERT_EQUAL_size_t(2, two.size());
	auto three = split("a::b");
	TEST_ASSERT_EQUAL_size_t(3, three.size());
	TEST_ASSERT_EQUAL_STRING("", three[1].c_str());
}

void testLegacyCapConstant() {
	TEST_ASSERT_EQUAL_size_t(2, MAX_LEGACY_SALTS);
}

int runUnityTests(void) {
	UNITY_BEGIN();
	RUN_TEST(testRelationHashesMatchCanonical);
	RUN_TEST(testObjectHashingMatchesCanonical);
	RUN_TEST(testIdTagMatchesCanonical);
	RUN_TEST(testCovers);
	RUN_TEST(testTruncatedTo16Bytes);
	RUN_TEST(testDefaultSaltIsFailOpenNulls);
	RUN_TEST(testSaltSensitivity);
	RUN_TEST(testSaltMustBe32Bytes);
	RUN_TEST(testSplitMatchesPythonSemantics);
	RUN_TEST(testLegacyCapConstant);
	return UNITY_END();
}

// For native dev-platform or for some embedded frameworks
int main(void) {
	return runUnityTests();
}

#ifdef ARDUINO
// For Arduino framework
void setup() {
	delay(2000);
	runUnityTests();
}
void loop() {}
#endif

// For ESP-IDF framework
void app_main() {
	runUnityTests();
}
