/*
 * Dacar C++ port — evaluation engine tests (§7, §10.2).
 *
 * Scenario fixtures (delegation chains, denies, cycles, bounds, multi-salt,
 * threshold-group anchors) are generated by the canonical Python
 * implementation together with the expected verdicts.
 *
 * Licensed under the EUPL-1.2 (see repository root).
 */

#include <unity.h>

#include "TestUtil.h"

using namespace Dacar;
using namespace DacarTest;

void setUp(void) {}
void tearDown(void) {}

void testEngineCasesMatchCanonical() {
	for (size_t i = 0; i < DacarFixtures::ENGINE_CASE_COUNT; i++) {
		const auto& c = *DacarFixtures::ENGINE_CASES[i];
		auto hashers = hashersFor(c.salt_hex, c.legacy_hex);
		auto anchors = bytesVecFromHex(c.anchors_hex);
		Dacar::Set<RNS::Bytes> anchor_set(anchors.begin(), anchors.end());
		Config config(
			anchor_set,
			bytesFromHex(c.salt_hex),
			[&]() {
				Dacar::Vector<RNS::Bytes> legacy;
				for (size_t j = 1; j < hashers.size(); j++) {
					legacy.push_back(hashers[j].salt());
				}
				return legacy;
			}()
		);
		StateVector state;
		for (size_t s = 0; s < c.step_count; s++) {
			TEST_ASSERT_EQUAL_UINT8(c.steps[s].expect, applyStep(state, c.steps[s], hashers));
		}
		Engine engine(config, state);
		for (size_t r = 0; r < c.request_count; r++) {
			const auto& req = c.requests[r];
			bool result = engine.evaluate(req.object, req.relation, bytesFromHex(req.grantee_hex));
			TEST_ASSERT_EQUAL_UINT8_MESSAGE(
				req.expected, result,
				(c.name != nullptr ? c.name : "") // per-case diagnostics
			);
		}
	}
}

void testEngineBoundsConfigurable() {
	// Engine bound parameters are exposed and default to the spec values.
	Config config({bytesFromHex(DacarFixtures::ENGINE_CASES[0]->anchors_hex)});
	StateVector state;
	Engine engine(config, state);
	TEST_ASSERT_EQUAL_INT(DEFAULT_MAX_DEPTH, 10);
	TEST_ASSERT_EQUAL_INT(DEFAULT_MAX_VISITED, 50);
}

void testEvaluateHashesEntryPoint() {
	// The §8 hashed-hypothesis entry point agrees with plaintext evaluate().
	const auto& c = *DacarFixtures::ENGINE_CASES[1]; // root_anchor_direct_grant
	auto hashers = hashersFor(c.salt_hex, c.legacy_hex);
	auto anchors = bytesVecFromHex(c.anchors_hex);
	Dacar::Set<RNS::Bytes> anchor_set(anchors.begin(), anchors.end());
	Config config(anchor_set, bytesFromHex(c.salt_hex));
	StateVector state;
	for (size_t s = 0; s < c.step_count; s++) {
		applyStep(state, c.steps[s], hashers);
	}
	Engine engine(config, state);
	const auto& req = c.requests[0];
	bool via_plaintext = engine.evaluate(req.object, req.relation, bytesFromHex(req.grantee_hex));

	Dacar::Vector<Hypothesis> hypotheses;
	for (const auto& hasher : config.hashers()) {
		auto [object_hashes, _w] = hasher.hash_object(req.object);
		Hypothesis hyp;
		hyp.hasher = hasher;
		hyp.object_hashes = std::move(object_hashes);
		hyp.allow_relation_hash = hasher.hash_relation(req.relation);
		hyp.deny_relation_hash = hasher.hash_relation(std::string("-") + req.relation);
		hypotheses.push_back(std::move(hyp));
	}
	bool via_hashes = engine.evaluate_hashes(bytesFromHex(req.grantee_hex), hypotheses);
	TEST_ASSERT_EQUAL_UINT8(via_plaintext, via_hashes);
	TEST_ASSERT_TRUE(via_hashes);
}

int runUnityTests(void) {
	UNITY_BEGIN();
	RUN_TEST(testEngineCasesMatchCanonical);
	RUN_TEST(testEngineBoundsConfigurable);
	RUN_TEST(testEvaluateHashesEntryPoint);
	return UNITY_END();
}

int main(void) {
	return runUnityTests();
}

#ifdef ARDUINO
void setup() {
	delay(2000);
	runUnityTests();
}
void loop() {}
#endif

void app_main() {
	runUnityTests();
}
