/*
 * Dacar C++ port — signed Operation / Delta tests (§5.2, §5.3).
 *
 * Byte-exact expectations (pre-images, Ed25519 signatures, transport
 * payloads) are generated by the canonical Python implementation. Because
 * Ed25519 signing is deterministic (RFC 8032), the C++ port re-signs with
 * the same seeds and must reproduce the reference signature bytes exactly.
 *
 * Licensed under the EUPL-1.2 (see repository root).
 */

#include <unity.h>

#include "TestUtil.h"

#include <stdexcept>
#include <string>

using namespace Dacar;
using namespace DacarTest;

void setUp(void) {}
void tearDown(void) {}

static Operation buildOperation(const DacarFixtures::OpCase& c) {
	NamespaceHasher hasher(bytesFromHex(c.salt_hex));
	Tuple t = Tuple::from_plaintext(
		c.object, c.relation, bytesFromHex(c.grantee_hex), bytesFromHex(c.issuer_hex), hasher
	);
	return Operation(t, (Action)c.action, c.hlc);
}

static std::vector<RNS::Cryptography::Ed25519PrivateKey::Ptr> keysFor(const char* signing_seeds) {
	std::vector<RNS::Cryptography::Ed25519PrivateKey::Ptr> keys;
	for (int idx : intVecFromJoined(signing_seeds)) {
		keys.push_back(keyFromSeed(bytesFromHex(DacarFixtures::KEYS[idx].seed_hex)));
	}
	return keys;
}

void testPreimagesMatchCanonical() {
	for (const auto& c : DacarFixtures::OP_CASES) {
		Operation op = buildOperation(c);
		TEST_ASSERT_EQUAL_STRING(c.preimage_hex, op.preimage().toHex().c_str());
	}
}

void testSignaturesMatchCanonical() {
	for (const auto& c : DacarFixtures::OP_CASES) {
		Operation unsigned_op = buildOperation(c);
		Operation signed_op = unsigned_op.sign(keysFor(c.signing_seeds));
		// Deterministic Ed25519: the C++ port reproduces the reference
		// Python signature bytes and the full transport payload byte-exactly.
		TEST_ASSERT_EQUAL_STRING(c.payload_hex, signed_op.to_payload().toHex().c_str());
	}
}

void testPayloadRoundtrip() {
	for (const auto& c : DacarFixtures::OP_CASES) {
		RNS::Bytes payload = bytesFromHex(c.payload_hex);
		Operation decoded = Operation::from_payload(payload);
		TEST_ASSERT_EQUAL_STRING(c.payload_hex, decoded.to_payload().toHex().c_str());
		// Decoded fields line up with the fixture definition.
		TEST_ASSERT_EQUAL_UINT8(c.action, (uint8_t)decoded.action());
		TEST_ASSERT_EQUAL_UINT64(c.hlc, decoded.hlc());
		TEST_ASSERT_TRUE(decoded.issuer() == bytesFromHex(c.issuer_hex));
		TEST_ASSERT_TRUE(decoded.grantee() == bytesFromHex(c.grantee_hex));
	}
}

void testVerifyAgainstCanonicalKeys() {
	for (const auto& c : DacarFixtures::OP_CASES) {
		RNS::Bytes payload = bytesFromHex(c.payload_hex);
		Operation decoded = Operation::from_payload(payload);
		auto pubs = bytesVecFromHex(c.member_pubs_hex);
		TEST_ASSERT_TRUE(decoded.verify_threshold(pubs, c.threshold));
		// Wrong threshold count rejected.
		TEST_ASSERT_FALSE(decoded.verify_threshold(pubs, c.threshold + 1));
	}
}

void testTamperDetection() {
	const auto& c = DacarFixtures::OP_CASES[0];
	std::string hex(c.payload_hex);
	// Flip the last hex digit: this corrupts the final signature byte.
	char last = hex[hex.size() - 1];
	hex[hex.size() - 1] = (last == '0') ? '1' : '0';
	Operation decoded = Operation::from_payload(bytesFromHex(hex.c_str()));
	auto pubs = bytesVecFromHex(c.member_pubs_hex);
	TEST_ASSERT_FALSE(decoded.verify_threshold(pubs, c.threshold));
	// A different (non-member) key never verifies either.
	TEST_ASSERT_FALSE(
		decoded.verify(bytesFromHex(DacarFixtures::KEYS[5].public_hex))
	);
}

void testNonMemberSignatureRejected() {
	const auto& c = DacarFixtures::OP_CASES[3]; // signed by seed 0
	Operation op = buildOperation(c);
	// Sign with member 0's key but verify against a keyset of other members.
	Operation signed_op = op.sign(keysFor(c.signing_seeds));
	Dacar::Vector<RNS::Bytes> pubs = bytesVecFromHex(DacarFixtures::KEYS[5].public_hex);
	TEST_ASSERT_FALSE(signed_op.verify(pubs[0]));
}

void testDuplicateMemberRejected() {
	const auto& c = DacarFixtures::OP_CASES[0];
	Operation op = buildOperation(c);
	// Two signatures from the SAME key against a 2-of-2 keyset of distinct
	// members: duplicate signatures must be rejected (§5.2).
	auto k0 = keyFromSeed(bytesFromHex(DacarFixtures::KEYS[0].seed_hex));
	Operation twice = op.sign({k0, k0});
	auto pubs = bytesVecFromHex(
		(std::string(DacarFixtures::KEYS[0].public_hex) + ";" + DacarFixtures::KEYS[1].public_hex).c_str()
	);
	TEST_ASSERT_FALSE(twice.verify_threshold(pubs, 2));
}

void testUnsignedPayloadRejected() {
	const auto& c = DacarFixtures::OP_CASES[0];
	Operation op = buildOperation(c);
	TEST_ASSERT_THROW(op.to_payload(), std::invalid_argument);
}

void testMalformedPayloadsRejected() {
	// Not an array (ASCII garbage).
	TEST_ASSERT_THROW(Operation::from_payload(RNS::Bytes("dacar")), std::invalid_argument);
	// Empty.
	TEST_ASSERT_THROW(Operation::from_payload(RNS::Bytes()), std::invalid_argument);
	// A msgpack value that is not an array.
	TEST_ASSERT_THROW(Operation::from_payload(bytesFromHex("C40101")), std::invalid_argument);
	// A valid array with the wrong arity (§5.3: exactly 8 elements).
	TEST_ASSERT_THROW(Operation::from_payload(bytesFromHex("93010203")), std::invalid_argument);
	// A valid 8-element array whose first field is an int, not a bin.
	TEST_ASSERT_THROW(
			Operation::from_payload(bytesFromHex("980102030405060708")), std::invalid_argument
	);
}

int runUnityTests(void) {
	UNITY_BEGIN();
	RUN_TEST(testPreimagesMatchCanonical);
	RUN_TEST(testSignaturesMatchCanonical);
	RUN_TEST(testPayloadRoundtrip);
	RUN_TEST(testVerifyAgainstCanonicalKeys);
	RUN_TEST(testTamperDetection);
	RUN_TEST(testNonMemberSignatureRejected);
	RUN_TEST(testDuplicateMemberRejected);
	RUN_TEST(testUnsignedPayloadRejected);
	RUN_TEST(testMalformedPayloadsRejected);
	return UNITY_END();
}

int main(void) {
	return runUnityTests();
}

#ifdef ARDUINO
void setup() {
	delay(2000);
	runUnityTests();
}
void loop() {}
#endif

void app_main() {
	runUnityTests();
}
