/*
 * Dacar C++ port — Strict Consistency Challenge tests (§8, work doc #16
 * Phase 3).
 *
 * Byte-exact fixture cases (§8.3 challenge payloads, §8.5 receipts, and
 * full AuthoritativeServer.handle() transcripts) are generated by the
 * canonical Python implementation. Client flows use injected fake
 * transports, mirroring the Python suite's approach.
 *
 * Licensed under the EUPL-1.2 (see repository root).
 */

#include <unity.h>

#include "TestUtil.h"

#include <stdexcept>
#include <vector>

using namespace Dacar;
using namespace DacarTest;

void setUp(void) {}
void tearDown(void) {}

static const char* FIXTURE_SALT_HEX = "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f";

static RNS::Bytes anchorId(uint8_t fill) {
	RNS::Bytes id(16);
	memset(id.writable(16), fill, 16);
	return id;
}

// An N-byte blob filled with `fill` (RNS::Bytes(n) only reserves capacity).
static RNS::Bytes fillBytes(size_t size, uint8_t fill = 0) {
	RNS::Bytes out;
	memset(out.writable(size), fill, size);
	return out;
}

static std::vector<NamespaceHasher> hashersFrom(const char* saltHex, const char* legacyHex) {
	std::vector<NamespaceHasher> hashers;
	hashers.emplace_back(bytesFromHex(saltHex));
	for (const auto& legacy : bytesVecFromHex(legacyHex)) {
		hashers.emplace_back(legacy);
	}
	return hashers;
}

// -- §8.3 Challenge ----------------------------------------------------------------

void testChallengePayloadMatchesPython() {
	for (size_t i = 0; i < DacarFixtures::CHALLENGE_CASE_COUNT; i++) {
		const auto& c = DacarFixtures::CHALLENGE_CASES[i];
		const Challenge challenge = Challenge::generate(
			c.object,
			c.relation,
			bytesFromHex(c.grantee_hex),
			hashersFrom(c.salt_hex, c.legacy_hex),
			bytesFromHex(c.nonce_hex)
		);
		const RNS::Bytes payload = challenge.to_payload();
		const RNS::Bytes expected = bytesFromHex(c.expected_hex);
		TEST_ASSERT_EQUAL_MEMORY(expected.data(), payload.data(), expected.size());
	}
}

void testChallengeGeneratesFreshNonce() {
	const Challenge a = Challenge::generate("o", "r", anchorId(1), hashersFrom(FIXTURE_SALT_HEX, ""));
	const Challenge b = Challenge::generate("o", "r", anchorId(1), hashersFrom(FIXTURE_SALT_HEX, ""));
	TEST_ASSERT_EQUAL_UINT32(NONCE_SIZE, a.nonce().size());
	TEST_ASSERT_TRUE(a.nonce() != b.nonce());
}

void testChallengeValidation() {
	// Wrong grantee length.
	TEST_ASSERT_THROW(
		Challenge("o", "r", RNS::Bytes(15), fillBytes(NONCE_SIZE), hashersFrom(FIXTURE_SALT_HEX, "")),
		std::invalid_argument
	);
	// Wrong nonce length.
	TEST_ASSERT_THROW(
		Challenge("o", "r", anchorId(1), RNS::Bytes(31), hashersFrom(FIXTURE_SALT_HEX, "")),
		std::invalid_argument
	);
	// No hashers.
	TEST_ASSERT_THROW(
		Challenge("o", "r", anchorId(1), fillBytes(NONCE_SIZE), {}),
		std::invalid_argument
	);
}

void testChallengeDecodeMatchesWire() {
	// Decoding a canonical payload yields the grantee, nonce and per-salt
	// entries bound to the generating salts.
	for (size_t i = 0; i < DacarFixtures::CHALLENGE_CASE_COUNT; i++) {
		const auto& c = DacarFixtures::CHALLENGE_CASES[i];
		const DecodedChallenge decoded = decode_challenge_payload(bytesFromHex(c.expected_hex));
		TEST_ASSERT_TRUE(decoded.nonce == bytesFromHex(c.nonce_hex));
		TEST_ASSERT_TRUE(decoded.grantee == bytesFromHex(c.grantee_hex));
		const auto hashers = hashersFrom(c.salt_hex, c.legacy_hex);
		TEST_ASSERT_EQUAL_size_t(hashers.size(), decoded.entries.size());
		for (size_t s = 0; s < hashers.size(); s++) {
			const auto& entry = decoded.entries[s];
			TEST_ASSERT_TRUE(entry.salt_id_tag == hashers[s].id_tag());
			TEST_ASSERT_TRUE(entry.allow_relation_hash == hashers[s].hash_relation(c.relation));
			std::string deny = std::string("-") + c.relation;
			TEST_ASSERT_TRUE(entry.deny_relation_hash == hashers[s].hash_relation(deny));
			auto objHashes = hashers[s].hash_object(c.object).first;
			TEST_ASSERT_EQUAL_size_t(objHashes.size(), entry.object_hashes.size());
			for (size_t o = 0; o < objHashes.size(); o++) {
				TEST_ASSERT_TRUE(objHashes[o] == entry.object_hashes[o]);
			}
		}
	}
}

void testChallengeDecodeRejectsMalformed() {
	for (size_t i = 0; i < DacarFixtures::CHALLENGE_MALFORMED_CASE_COUNT; i++) {
		const auto& c = DacarFixtures::CHALLENGE_MALFORMED_CASES[i];
		TEST_ASSERT_THROW(decode_challenge_payload(bytesFromHex(c.payload_hex)), std::invalid_argument);
	}
	// Truncated garbage as well.
	TEST_ASSERT_THROW(decode_challenge_payload(RNS::Bytes()), std::invalid_argument);
	TEST_ASSERT_THROW(decode_challenge_payload(bytesFromHex("c0")), std::invalid_argument);
}

// -- §8.5 Receipt ------------------------------------------------------------------

void testReceiptPayloadMatchesPython() {
	for (size_t i = 0; i < DacarFixtures::RECEIPT_CASE_COUNT; i++) {
		const auto& c = DacarFixtures::RECEIPT_CASES[i];
		const Receipt receipt(
			(Verdict)c.verdict,
			c.server_hlc,
			bytesFromHex(c.nonce_hex),
			RNS::Bytes()  // sign below with the fixture key
		);
		// Pre-image is the canonical byte concatenation.
		const RNS::Bytes preimage = receipt.preimage();
		const RNS::Bytes expectedPreimage = bytesFromHex(c.preimage_hex);
		TEST_ASSERT_EQUAL_MEMORY(expectedPreimage.data(), preimage.data(), expectedPreimage.size());

		const Receipt signedReceipt = receipt.sign(
			RNS::Cryptography::Ed25519PrivateKey::from_private_bytes(
				bytesFromHex(DacarFixtures::KEYS[c.key_index].seed_hex)
			)
		);
		const RNS::Bytes payload = signedReceipt.to_payload();
		const RNS::Bytes expected = bytesFromHex(c.payload_hex);
		TEST_ASSERT_EQUAL_MEMORY(expected.data(), payload.data(), expected.size());

		// Round-trip through the payload keeps the verdict and verifies.
		const Receipt decoded = Receipt::from_payload(expected);
		TEST_ASSERT_EQUAL_INT(c.verdict, (int)decoded.verdict());
		TEST_ASSERT_EQUAL_UINT64(c.server_hlc, decoded.server_hlc());
		TEST_ASSERT_TRUE(decoded.nonce() == bytesFromHex(c.nonce_hex));
		TEST_ASSERT_TRUE(decoded.verify(bytesFromHex(DacarFixtures::KEYS[c.key_index].public_hex)));
	}
}

void testReceiptUnsignedCannotSerialize() {
	const Receipt receipt(Verdict::ALLOW, 1, fillBytes(NONCE_SIZE));
	TEST_ASSERT_THROW(receipt.to_payload(), std::invalid_argument);
}

void testReceiptValidation() {
	TEST_ASSERT_THROW(Receipt(Verdict::ALLOW, 1, RNS::Bytes(31)), std::invalid_argument);
	TEST_ASSERT_THROW(
		Receipt(Verdict::ALLOW, 1, fillBytes(NONCE_SIZE), fillBytes(63)),
		std::invalid_argument
	);
}

void testReceiptVerifyRejectsTampering() {
	const Receipt receipt = Receipt(Verdict::ALLOW, 42, fillBytes(NONCE_SIZE)).sign(
		RNS::Cryptography::Ed25519PrivateKey::from_private_bytes(
			bytesFromHex(DacarFixtures::KEYS[0].seed_hex)
		)
	);
	const RNS::Bytes pub0 = bytesFromHex(DacarFixtures::KEYS[0].public_hex);
	const RNS::Bytes pub1 = bytesFromHex(DacarFixtures::KEYS[1].public_hex);
	TEST_ASSERT_TRUE(receipt.verify(pub0));
	// Wrong key.
	TEST_ASSERT_FALSE(receipt.verify(pub1));
	// Flipped verdict (signature no longer matches the preimage).
	const Receipt flipped(Verdict::DENY, receipt.server_hlc(), receipt.nonce(), receipt.signature());
	TEST_ASSERT_FALSE(flipped.verify(pub0));
	// All-zero signature.
	const Receipt tamperedSig(Verdict::ALLOW, 42, fillBytes(NONCE_SIZE), fillBytes(64));
	TEST_ASSERT_FALSE(tamperedSig.verify(pub0));
}

// -- §8.4 AuthoritativeServer --------------------------------------------------------

static Config serverConfig(const DacarFixtures::ServerCase& c, Dacar::Set<RNS::Bytes>& anchors) {
	auto anchorVec = bytesVecFromHex(c.anchors_hex);
	anchors = Dacar::Set<RNS::Bytes>(anchorVec.begin(), anchorVec.end());
	return Config(
		anchors,
		bytesFromHex(c.salt_hex),
		bytesVecFromHex(c.legacy_hex),
		{},
		bytesFromHex(c.authoritative_hex)
	);
}

void testAuthoritativeServerMatchesPython() {
	for (size_t i = 0; i < DacarFixtures::SERVER_CASE_COUNT; i++) {
		const auto& c = *DacarFixtures::SERVER_CASES[i];
		Dacar::Set<RNS::Bytes> anchors;
		Config config = serverConfig(c, anchors);
		StateVector state(config.deletion_horizon_days());
		auto hashers = hashersFor(c.salt_hex, c.legacy_hex);
		for (size_t s = 0; s < c.step_count; s++) {
			TEST_ASSERT_TRUE(applyStep(state, c.steps[s], hashers));
		}
		// Seeded far-future clock -> purely logical (deterministic) now().
		AuthoritativeServer server(config, state, keyFromSeed(bytesFromHex(DacarFixtures::KEYS[0].seed_hex)), Clock(0xFFFFFFFFFFF0ULL, 0));
		const RNS::Bytes receiptPayload = server.handle(bytesFromHex(c.challenge_hex));
		const RNS::Bytes expected = bytesFromHex(c.receipt_hex);
		TEST_ASSERT_EQUAL_MEMORY(expected.data(), receiptPayload.data(), expected.size());

		// The verdict matches, the nonce echoes, and the signature verifies
		// against the server's public key.
		const Receipt receipt = Receipt::from_payload(receiptPayload);
		TEST_ASSERT_EQUAL_INT(c.verdict, (int)receipt.verdict());
		TEST_ASSERT_TRUE(receipt.nonce() == bytesFromHex("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f"));
		TEST_ASSERT_TRUE(receipt.verify(bytesFromHex(DacarFixtures::KEYS[0].public_hex)));
	}
}

void testAuthoritativeServerRejectsMalformedChallenge() {
	Dacar::Set<RNS::Bytes> anchors{anchorId(1)};
	Config config(anchors, bytesFromHex(FIXTURE_SALT_HEX), {}, {}, anchorId(1));
	StateVector state;
	AuthoritativeServer server(config, state, keyFromSeed(bytesFromHex(DacarFixtures::KEYS[0].seed_hex)));
	TEST_ASSERT_THROW(server.handle(RNS::Bytes()), std::invalid_argument);
	TEST_ASSERT_THROW(server.handle(bytesFromHex("c0")), std::invalid_argument);
}

// -- ChallengeClient (§8.1–§8.6) -------------------------------------------------------

struct ClientWorld {
	Dacar::Set<RNS::Bytes> anchors;
	Config config;
	StateVector state;
	Engine engine;

	explicit ClientWorld(const char* saltHex = FIXTURE_SALT_HEX, const char* legacyHex = "")
		: config(Dacar::Set<RNS::Bytes>{anchorId(1)}, bytesFromHex(saltHex), bytesVecFromHex(legacyHex), {}, anchorId(1)),
		  state(config.deletion_horizon_days()),
		  engine(config, state)
	{}
};

void testClientRequiresAuthoritativeIdentity() {
	Config config(Dacar::Set<RNS::Bytes>{anchorId(1)}, bytesFromHex(FIXTURE_SALT_HEX));
	StateVector state;
	TEST_ASSERT_THROW(
		ChallengeClient(config, state, fillBytes(PUBLIC_KEY_SIZE), nullptr),
		std::invalid_argument
	);
}

void testClientLocalDenyShortCircuits() {
	// No grant in state: the §8.1 local pre-check denies without ever
	// consulting the transport.
	ClientWorld world;
	const RNS::Bytes bob = anchorId(3);
	bool transportCalled = false;
	ChallengeClient client(
		world.config,
		world.state,
		fillBytes(PUBLIC_KEY_SIZE),
		[&transportCalled](const RNS::Bytes&) {
			transportCalled = true;
			return RNS::Bytes();
		}
	);
	TEST_ASSERT_FALSE(client.authorize("buzzer", "sound", bob));
	TEST_ASSERT_FALSE(transportCalled);
}

void testClientAcceptsVerifiedAllow() {
	ClientWorld world;
	// Grant: anchor(1) -> bob for buzzer:sound.
	const uint64_t stamp = DacarFixtures::HLC_CASES[2].packed;
	world.state.apply(
		Operation(
			Tuple::from_plaintext("buzzer", "sound", anchorId(3), anchorId(1), world.config.primary_hasher()),
			Action::GRANT,
			stamp
		),
		(stamp >> 16) + 10000
	);

	const RNS::Bytes serverPub = bytesFromHex(DacarFixtures::KEYS[0].public_hex);
	auto serverKey = keyFromSeed(bytesFromHex(DacarFixtures::KEYS[0].seed_hex));

	// Fake transport: run the authoritative server over the same request.
	// The server's salt/state mirror the client's (single-node loopback).
	Dacar::Set<RNS::Bytes> anchors{anchorId(1)};
	Config serverConfigCfg(anchors, world.config.primary_salt(), {}, {}, anchorId(1));
	StateVector& serverState = world.state;
	AuthoritativeServer server(serverConfigCfg, serverState, serverKey, Clock(0xFFFFFFFFFFF0ULL, 0));

	ChallengeClient client(
		world.config,
		world.state,
		serverPub,
		[&server](const RNS::Bytes& challengePayload) {
			return server.handle(challengePayload);
		}
	);
	TEST_ASSERT_TRUE(client.authorize("buzzer", "sound", anchorId(3)));
	// A request for a relation nobody holds is denied end to end.
	TEST_ASSERT_FALSE(client.authorize("buzzer", "wipe", anchorId(3)));
}

void testClientDeniesOnPartition() {
	ClientWorld world;
	const uint64_t stamp = DacarFixtures::HLC_CASES[2].packed;
	world.state.apply(
		Operation(
			Tuple::from_plaintext("buzzer", "sound", anchorId(3), anchorId(1), world.config.primary_hasher()),
			Action::GRANT,
			stamp
		),
		(stamp >> 16) + 10000
	);
	// Transport returning empty (unreachable) -> §8 partition -> DENY.
	ChallengeClient unreachable(
		world.config,
		world.state,
		fillBytes(PUBLIC_KEY_SIZE),
		[](const RNS::Bytes&) {
			return RNS::Bytes();
		}
	);
	TEST_ASSERT_FALSE(unreachable.authorize("buzzer", "sound", anchorId(3)));
	// Transport throwing -> same partition penalty.
	ChallengeClient throwing(
		world.config,
		world.state,
		fillBytes(PUBLIC_KEY_SIZE),
		[](const RNS::Bytes&) -> RNS::Bytes {
			throw std::runtime_error("link down");
		}
	);
	TEST_ASSERT_FALSE(throwing.authorize("buzzer", "sound", anchorId(3)));
}

void testClientDeniesOnBadReceipt() {
	ClientWorld world;
	const uint64_t stamp = DacarFixtures::HLC_CASES[2].packed;
	world.state.apply(
		Operation(
			Tuple::from_plaintext("buzzer", "sound", anchorId(3), anchorId(1), world.config.primary_hasher()),
			Action::GRANT,
			stamp
		),
		(stamp >> 16) + 10000
	);
	const RNS::Bytes serverPub = bytesFromHex(DacarFixtures::KEYS[0].public_hex);
	auto serverKey = keyFromSeed(bytesFromHex(DacarFixtures::KEYS[0].seed_hex));
	Dacar::Set<RNS::Bytes> anchors{anchorId(1)};
	Config serverConfigCfg(anchors, world.config.primary_salt(), {}, {}, anchorId(1));
	AuthoritativeServer server(serverConfigCfg, world.state, serverKey, Clock(0xFFFFFFFFFFF0ULL, 0));

	// A receipt signed by the WRONG key (not the configured authoritative
	// identity) must not authenticate an allow.
	auto impostorKey = keyFromSeed(bytesFromHex(DacarFixtures::KEYS[1].seed_hex));
	ChallengeClient impostor(
		world.config,
		world.state,
		serverPub,
		[&server, &impostorKey](const RNS::Bytes& challengePayload) {
			const DecodedChallenge decoded = decode_challenge_payload(challengePayload);
			// Evaluate honestly but sign with the impostor's key.
			const Receipt receipt = Receipt(Verdict::ALLOW, 1, decoded.nonce).sign(impostorKey);
			return receipt.to_payload();
		}
	);
	TEST_ASSERT_FALSE(impostor.authorize("buzzer", "sound", anchorId(3)));

	// A tampered nonce in an otherwise valid receipt must fail the check.
	ChallengeClient tampered(
		world.config,
		world.state,
		serverPub,
		[&server](const RNS::Bytes& challengePayload) {
			const DecodedChallenge decoded = decode_challenge_payload(challengePayload);
			RNS::Bytes wrongNonce = fillBytes(NONCE_SIZE, 0xEE);
			const Receipt receipt = Receipt(Verdict::ALLOW, 1, wrongNonce).sign(
				RNS::Cryptography::Ed25519PrivateKey::from_private_bytes(
					bytesFromHex(DacarFixtures::KEYS[0].seed_hex)
				)
			);
			return receipt.to_payload();
		}
	);
	TEST_ASSERT_FALSE(tampered.authorize("buzzer", "sound", anchorId(3)));

	// A garbage payload instead of a receipt -> DENY.
	ChallengeClient garbage(
		world.config,
		world.state,
		serverPub,
		[](const RNS::Bytes&) {
			return bytesFromHex("deadbeef");
		}
	);
	TEST_ASSERT_FALSE(garbage.authorize("buzzer", "sound", anchorId(3)));
}

void testClientDenyVerdictFailsEvenWhenValid() {
	ClientWorld world;
	const uint64_t stamp = DacarFixtures::HLC_CASES[2].packed;
	world.state.apply(
		Operation(
			Tuple::from_plaintext("buzzer", "sound", anchorId(3), anchorId(1), world.config.primary_hasher()),
			Action::GRANT,
			stamp
		),
		(stamp >> 16) + 10000
	);
	const RNS::Bytes serverPub = bytesFromHex(DacarFixtures::KEYS[0].public_hex);
	// A validly signed DENY verdict fails the operation (§8.6).
	ChallengeClient denied(
		world.config,
		world.state,
		serverPub,
		[&serverPub](const RNS::Bytes& challengePayload) {
			const DecodedChallenge decoded = decode_challenge_payload(challengePayload);
			const Receipt receipt = Receipt(Verdict::DENY, 7, decoded.nonce).sign(
				RNS::Cryptography::Ed25519PrivateKey::from_private_bytes(
					bytesFromHex(DacarFixtures::KEYS[0].seed_hex)
				)
			);
			return receipt.to_payload();
		}
	);
	TEST_ASSERT_FALSE(denied.authorize("buzzer", "sound", anchorId(3)));
}

int runUnityTests(void) {
	UNITY_BEGIN();
	RUN_TEST(testChallengePayloadMatchesPython);
	RUN_TEST(testChallengeGeneratesFreshNonce);
	RUN_TEST(testChallengeValidation);
	RUN_TEST(testChallengeDecodeMatchesWire);
	RUN_TEST(testChallengeDecodeRejectsMalformed);
	RUN_TEST(testReceiptPayloadMatchesPython);
	RUN_TEST(testReceiptUnsignedCannotSerialize);
	RUN_TEST(testReceiptValidation);
	RUN_TEST(testReceiptVerifyRejectsTampering);
	RUN_TEST(testAuthoritativeServerMatchesPython);
	RUN_TEST(testAuthoritativeServerRejectsMalformedChallenge);
	RUN_TEST(testClientRequiresAuthoritativeIdentity);
	RUN_TEST(testClientLocalDenyShortCircuits);
	RUN_TEST(testClientAcceptsVerifiedAllow);
	RUN_TEST(testClientDeniesOnPartition);
	RUN_TEST(testClientDeniesOnBadReceipt);
	RUN_TEST(testClientDenyVerdictFailsEvenWhenValid);
	return UNITY_END();
}

int main(void) {
	return runUnityTests();
}

#ifdef ARDUINO
void setup() {
	delay(2000);
	runUnityTests();
}
void loop() {}
#endif

void app_main() {
	runUnityTests();
}
